### ISSUE TITLE
Screen Sharing Adjust Resolution

### ISSUE THREAD

**Issue by brickgale** [nttcom/SkyWay-ScreenShare#32]
Is there by any chance we can adjust screen sharing resolution to be clearer? Like appear.in.

**Comment by Mrsevic** [comment]
Look at the documentation and sample more carefully. It is there.

**Comment by brickgale** [comment]
@Mrsevic btw had already fixed this issue, i get that we can set width and height for adjusting resolution on the docs but it didn't say it needed `autoplay` attribute for video tag. without the attribute, screen sharing will appear a bit glitchy and pixelated.

**Comment by Mrsevic** [comment]
Thanks, I did not know that. I had a bit of problem making this play nicely with Firefox using original peerjs library. If you happen to know anything about ICE candidates not found please let me know.

Thanks

**Comment by brickgale** [comment]
@Mrsevic have you already made firefox extension/plugin? actually im using original peerjs on my local pointing to a heroku hosted peerjs-server, and let production point to skyway.

**Comment by iwashi** [comment]
This comment is kind of off topic but we have the new repository for screen-share: https://github.com/skyway/skyway-screenshare. The new one implements more modern API like Promise. Also due to Firefox improvement you don't need Firefox extension/plugin.

**Comment by Mrsevic** [comment]
@brickgale Thank you for your kind response. To be honest I just want to share from Chrome with extension towards Firefox without, Firefox initially receives the stream but after 5 seconds it cancels it due to lack of ICE candidates. It is all happening on both original peerJS and modified one for Firefox.

@iwashi Thank you very much, I'll check it out for sure.

**Comment by brickgale** [comment]
@iwashi We can have screen sharing without an extension/plugin? only on firefox? Will check it out. Thank you so much.

**Comment by iwashi** [comment]
@brickgale right, only firefox doesn't require extension/plugin.
